import { Scenario } from "./types";

export const SCENARIOS: Scenario[] = [
  {
    id: 1,
    name: "Legitimate merchant payment",
    amount: 450,
    amountFormatted: "₹450",
    beneficiaryName: "Raju Kirana Store",
    beneficiaryVpa: "raju.store@okicici",
    description: "Payment for groceries",
    isFirstTimeBeneficiary: false,
    previousTransactionCount: 12,
    averageTransactionAmount: 420,
    deviceSignals: {
      screenSharing: false,
      accessibilityServicesActive: false,
      sameCity: true,
      unusualTime: false,
    },
    behavioralSignals: {
      referralSource: "direct",
    },
    expectedSeverity: "GREEN",
  },
  {
    id: 2,
    name: "First-time beneficiary",
    amount: 500,
    amountFormatted: "₹500",
    beneficiaryName: "Priya Sharma",
    beneficiaryVpa: "priya.s.2024@paytm",
    description: "Sending money",
    isFirstTimeBeneficiary: true,
    previousTransactionCount: 0,
    averageTransactionAmount: 450,
    deviceSignals: {
      screenSharing: false,
      accessibilityServicesActive: false,
      sameCity: true,
      unusualTime: false,
    },
    behavioralSignals: {
      referralSource: "direct",
    },
    expectedSeverity: "AMBER",
  },
  {
    id: 3,
    name: "OLX cashback scam",
    amount: 18000,
    amountFormatted: "₹18,000",
    beneficiaryName: "Quick Pay Store 247",
    beneficiaryVpa: "quickpay.store247@ybl",
    description: "Payment for OLX Laptop - Approve to receive Rs 18,000",
    isFirstTimeBeneficiary: true,
    previousTransactionCount: 0,
    averageTransactionAmount: 850,
    deviceSignals: {
      screenSharing: false,
      accessibilityServicesActive: false,
      sameCity: false,
      unusualTime: false,
    },
    behavioralSignals: {
      referralSource: "whatsapp_link",
      sessionAnomalies: ["navigated from WhatsApp shared link"],
    },
    expectedSeverity: "RED",
  },
  {
    id: 4,
    name: "Digital arrest coercion",
    amount: 250000,
    amountFormatted: "₹2,50,000",
    beneficiaryName: "Govt Verification Cell",
    beneficiaryVpa: "govt.verification.cell@ybl",
    description: "RBI Escrow Verification - Mandatory compliance deposit",
    isFirstTimeBeneficiary: true,
    previousTransactionCount: 0,
    averageTransactionAmount: 1200,
    deviceSignals: {
      screenSharing: false,
      accessibilityServicesActive: false,
      sameCity: true,
      unusualTime: false,
    },
    behavioralSignals: {
      referralSource: "direct",
      recentSearches: ["police complaint", "cyber crime", "arrest warrant"],
      sessionAnomalies: ["searched 'police complaint' 5 minutes ago"],
    },
    expectedSeverity: "RED",
  },
  {
    id: 5,
    name: "Fake customer care + screen share",
    amount: 15000,
    amountFormatted: "₹15,000",
    beneficiaryName: "Helpdesk Refund",
    beneficiaryVpa: "helpdesk.refund@okaxis",
    description: "Refund processing - Enter PIN to receive refund",
    isFirstTimeBeneficiary: true,
    previousTransactionCount: 0,
    averageTransactionAmount: 950,
    deviceSignals: {
      screenSharing: true,
      accessibilityServicesActive: true,
      accessibilityApp: "AnyDesk",
      sameCity: true,
      unusualTime: false,
    },
    behavioralSignals: {
      referralSource: "phone_call",
      sessionAnomalies: ["AnyDesk accessibility service detected active"],
    },
    expectedSeverity: "RED",
  },
];

export const RECENT_TRANSACTIONS = [
  {
    id: "t1",
    name: "Raju Kirana Store",
    vpa: "raju.store@okicici",
    amount: -420,
    date: "Today, 10:32 AM",
    type: "payment",
    icon: "🛒",
  },
  {
    id: "t2",
    name: "Salary Credit",
    vpa: "payroll@hdfc",
    amount: 45000,
    date: "Yesterday, 9:00 AM",
    type: "credit",
    icon: "💼",
  },
  {
    id: "t3",
    name: "Ankit Mehta",
    vpa: "ankit.m@oksbi",
    amount: -1200,
    date: "Apr 17, 8:45 PM",
    type: "payment",
    icon: "👤",
  },
  {
    id: "t4",
    name: "Swiggy",
    vpa: "swiggy@icici",
    amount: -340,
    date: "Apr 16, 1:15 PM",
    type: "payment",
    icon: "🍔",
  },
];
